version: '3.9'

services:
  landcharms-app:
    image: 'landcharms:latest'
    ports:
      - "8080:8080"
    build:
      context: .
    container_name: landcharms-app
    depends_on:
      landcharms-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://landcharms-db:5433/landcharms-db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=user
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=local
      - SERVER_PORT=8080
      - MANAGEMENT_PORT=9090
    networks:
      - default

  landcharms-db:
    image: 'postgres:14.4-alpine'
    container_name: landcharms-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=landcharms-db
    ports:
      - "5432:5432"
    networks:
      - default
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d" ]
      interval: 1s
      timeout: 3s
      retries: 10


networks:
  default:
    name: landcharms
    external: false