spring:
  boot:
    admin:
      client:
        url: http://localhost:8080

  security:
    user:
      name: teste
      password: 123456
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
  config:
    import: "optional:configserver:"
  application:
    name: landcharms

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /docs

management:
  endpoints:
    web:
      exposure:
        include: health, info, openapi, swagger-ui

  endpoint:
    health:
      show-details: ALWAYS



